apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e2nd65qwj-go
  janus-idp.io/tekton: e2nd65qwj-go
  backstage.io/kubernetes-id: e2nd65qwj-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: e2nd65qwj-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
